### ISSUE TITLE
数字显示Bug

### ISSUE THREAD

**Issue by Mr-clowns** [vangleer/vue3-odometer#1]
我在vivo x80 pro上显示99999的时候，在上翻的过程中，最后三位数字会消失掉，直到达到99999后才会重新显示。 所以只能看到前两位数字的滚动效果

**Comment by vangleer** [comment]
我安装了个手机模拟器，在模拟器上看效果没问题呀

**Comment by Mr-clowns** [comment]
是安卓模拟器嘛   可能只有部分机型有这个问题   我是在真机上遇到的这个bug   ios模拟器上我看是没问题的

**Comment by vangleer** [comment]
对，安卓模拟器，设备型号选的就是 vivo x80 pro
