### ISSUE TITLE
数字上翻抖动

### ISSUE THREAD

**Issue by Mr-clowns** [vangleer/vue3-odometer#2]
在数字位数比较大的情况下(在6位数的时候感知很明显)，数字在上翻过程中会出现左右抖动的问题，尤其是数字1，可能和数字本身的宽度有关，请问有好的解决办法吗

**Comment by vangleer** [comment]
可以发个动图吗，我测试没有呀

**Comment by Mr-clowns** [comment]
这里好像没法发图片  我获取dom元素强行给dom加了固定宽度  解决了抖动的那个问题。 那个抖动的原因就是数字宽度不固定引起的
